version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/CSDB
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=Password
      - JWT_SECRET_KEY="MzJieXRlc2xvbmdzZWNyZXRzZWNyZXRzZWNyZXRzZW8="
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=CSDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
